import{a as A,S as b,i as o}from"./assets/vendor-c493984e.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))h(t);new MutationObserver(t=>{for(const i of t)if(i.type==="childList")for(const m of i.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&h(m)}).observe(document,{childList:!0,subtree:!0});function r(t){const i={};return t.integrity&&(i.integrity=t.integrity),t.referrerPolicy&&(i.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?i.credentials="include":t.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function h(t){if(t.ep)return;t.ep=!0;const i=r(t);fetch(t.href,i)}})();const v="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEaSURBVHgBrZZhDoIwDIUL0fjXo3gUb7R5Er0BHsXD7A+bASlhYeC6V4WXGCHr3reNtkAkqG2D9T70mh/HSj4HybyqyPQ9PeuaXlRQ19GFY4c5dDodLSHNK3/fSam29Q+0k7/N1ZAt5hCyh7kIKZl77y/IMBezgEwXTW4ienBxcc65DCQ0PDYCQghGMDASJJpzTG4ue0KABEHmKeBAQEPx3LiIhmKy/M+aitDyGJoPAWsI32vNWTXpVQnXRal2kPQmO7pPx6XpPRCQmsdjSZ8JhIA0FbOllMKsRZqCQoMpXCy0GJRrFc7hVpGLSVqFWaxk52ZnVgPbIaL5HhBovgVSMv+qg7kt9JznZ+VL//pL+5hWFXei+mwRj+UDSHQ9vnHBEYAAAAAASUVORK5CYII=",u=e=>`
  <li class='gallery-item'>
    <a class='gallery-link' href='${e.largeImageURL}'>
      <img
        class='gallery-image'
        src='${e.webformatURL}'
        alt='${e.tags}'
        width=360
        height=152/>
    </a>
    <ul class='photo-info-list'>
      <li class='photo-info-list-item'><h2>Likes</h2><p>${e.likes}</p></li>
      <li class='photo-info-list-item'><h2>Views</h2><p>${e.views}</p></li>
      <li class='photo-info-list-item'><h2>Comments</h2><p>${e.comments}</p></li>
      <li class='photo-info-list-item'><h2>Downloads</h2><p>${e.downloads}</p></li>
    </ul>
  </li>`;A.defaults.baseURL="https://pixabay.com/";const y=(e,s)=>{const r={params:{key:"45417636-6e508772373129b2f08d1fd3e",q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:s}};return A.get("/api/",r)},g=v,p=document.querySelector(".form"),d=document.querySelector(".loader"),n=document.querySelector(".gallery"),a=document.querySelector(".js-load-more-btn");let l=1,c="",f=0;const L=new b(".gallery a",{captionsData:"alt",captionDelay:250,overlayOpacity:.8}),S=async e=>{try{if(e.preventDefault(),c=p.elements.search_img.value.trim(),l=1,!c){o.warning({title:"Warning",message:"Please fill the search field first.",position:"topRight"});return}d.classList.add("is-visible");const s=await y(c,l);if(s.data.hits.length===0){a.classList.add("is-hidden"),o.error({iconUrl:g,message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",position:"topRight",color:"#ef4040",maxWidth:"350px"}),n.innerHTML="";return}const r=s.data.hits.map(u).join("");n.innerHTML=r,f=n.querySelector("li").getBoundingClientRect().height,s.data.totalHits>15&&a.classList.remove("is-hidden"),L.refresh(),p.reset()}catch(s){o.error({iconUrl:g,message:s.message,messageColor:"white",position:"topRight",color:"#ef4040",maxWidth:"350px"})}finally{d.classList.remove("is-visible")}},w=async()=>{try{l++,a.classList.add("is-hidden"),d.classList.add("is-visible");const e=await y(c,l),s=e.data.hits.map(r=>u(r)).join("");n.insertAdjacentHTML("beforeend",s),L.refresh(),scrollBy({top:f*2,behavior:"smooth"}),a.classList.remove("is-hidden"),l===Math.ceil(e.data.totalHits/15)&&(a.classList.add("is-hidden"),o.warning({title:"Info",message:"Were sorry, but youve reached the end of search results.",position:"topRight"}))}catch(e){o.error({iconUrl:g,message:e.message,messageColor:"white",position:"topRight",color:"#ef4040",maxWidth:"350px"})}finally{d.classList.remove("is-visible")}};p.addEventListener("submit",S);a.addEventListener("click",w);
//# sourceMappingURL=commonHelpers.js.map
