import{a as A,i as g,S as u}from"./assets/vendor-c493984e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const h of i.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&d(h)}).observe(document,{childList:!0,subtree:!0});function r(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerPolicy&&(i.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?i.credentials="include":e.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function d(e){if(e.ep)return;e.ep=!0;const i=r(e);fetch(e.href,i)}})();const L="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAEaSURBVHgBrZZhDoIwDIUL0fjXo3gUb7R5Er0BHsXD7A+bASlhYeC6V4WXGCHr3reNtkAkqG2D9T70mh/HSj4HybyqyPQ9PeuaXlRQ19GFY4c5dDodLSHNK3/fSam29Q+0k7/N1ZAt5hCyh7kIKZl77y/IMBezgEwXTW4ienBxcc65DCQ0PDYCQghGMDASJJpzTG4ue0KABEHmKeBAQEPx3LiIhmKy/M+aitDyGJoPAWsI32vNWTXpVQnXRal2kPQmO7pPx6XpPRCQmsdjSZ8JhIA0FbOllMKsRZqCQoMpXCy0GJRrFc7hVpGLSVqFWaxk52ZnVgPbIaL5HhBovgVSMv+qg7kt9JznZ+VL//pL+5hWFXei+mwRj+UDSHQ9vnHBEYAAAAAASUVORK5CYII=",y=s=>`
  <li class='gallery-item'>
    <a class='gallery-link' href='${s.largeImageURL}'>
      <img
        class='gallery-image'
        src='${s.webformatURL}'
        alt='${s.tags}'
        width=360
        height=152/>
    </a>
    <ul class='photo-info-list'>
      <li class='photo-info-list-item'><h2>Likes</h2><p>${s.likes}</p></li>
      <li class='photo-info-list-item'><h2>Views</h2><p>${s.views}</p></li>
      <li class='photo-info-list-item'><h2>Comments</h2><p>${s.comments}</p></li>
      <li class='photo-info-list-item'><h2>Downloads</h2><p>${s.downloads}</p></li>
    </ul>
  </li>`;A.defaults.baseURL="https://pixabay.com/";const p=(s,t)=>{const r={params:{key:"45417636-6e508772373129b2f08d1fd3e",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:t}};return A.get("/api",r)},v=L,l=document.querySelector(".form"),c=document.querySelector(".loader"),m=document.querySelector(".gallery"),a=document.querySelector(".js-load-more-btn");let o=1,n="",f=0;const b=async s=>{try{s.preventDefault(),n=l.elements.search_img.value.trim(),o=1,a.classList.add("is-hidden");const t=await p(n,o);if(!n){g.warning({title:"Warning",message:"Please fill the search field first.",position:"topRight"}),l.elements.search_img.value="";return}if(c.classList.add("is-visible"),p(n,o),t.data.hits.length===0){g.error({iconUrl:`${v}`,message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",position:"topRight",color:"#ef4040",maxWidth:"350px"}),c.classList.remove("is-visible"),m.innerHTML="",l.reset();return}const r=t.data.hits.map(i=>y(i)).join("");m.innerHTML=r,f=m.querySelector("li").getBoundingClientRect().height,a.classList.remove("is-hidden"),new u(".gallery a",{captionsData:"alt",captionDelay:250,overlayOpacity:.8}).refresh(),c.classList.remove("is-visible"),l.reset()}catch(t){console.log(t)}},S=async s=>{try{o++,a.classList.add("is-hidden"),c.classList.add("is-visible");const t=await p(n,o),r=t.data.hits.map(e=>y(e)).join("");m.insertAdjacentHTML("beforeend",r);const d=new u(".gallery a",{captionsData:"alt",captionDelay:250,overlayOpacity:.8});scrollBy({top:f*2,behavior:"smooth"}),c.classList.remove("is-visible"),a.classList.remove("is-hidden"),o===t.data.totalHits&&(a.classList.add("is-hidden"),g.warning({title:"Info",message:"Were sorry, but youve reached the end of search results.",position:"topRight"}))}catch(t){console.log(t)}};l.addEventListener("submit",b);a.addEventListener("click",S);
//# sourceMappingURL=commonHelpers.js.map
